<a href="https://colab.research.google.com/github/Keistkmiya/Tugas3-Practical_Linear_Algebra_for_Data_Science/blob/main/Tugas3_Chapter9_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 9: Orthogonal Matrices and QR Decomposition

## Orthogonal Matrices and QR Decomposition

Matriks ortogonal adalah matriks persegi yang kolom-kolomnya merupakan vektor ortonormal, sehingga memenuhi sifat di mana hasil transpose matriks sama dengan inversnya ($Q^T = Q^{-1}$). QR Decomposition adalah metode dekomposisi yang memecah sebuah matriks $A$ menjadi dua matriks komponen, yaitu matriks ortogonal $Q$ dan matriks segitiga atas $R$ ($A = QR$). Teknik ini sangat stabil secara numerik dan digunakan secara luas sebagai fondasi untuk menyelesaikan masalah sistem persamaan linear serta algoritma pengorbanan kuadrat terkecil (least squares). NumPy menyediakan fungsi `np.linalg.qr()` untuk menghitung dekomposisi ini secara langsung.

In [1]:
import numpy as np

A = np.array([[1, -1, 4], [1, 4, -2], [1, 4, 2]])
Q, R = np.linalg.qr(A)

print(Q)
print(R)
print(np.round(Q @ R))

[[-5.77350269e-01  8.16496581e-01 -2.21595527e-16]
 [-5.77350269e-01 -4.08248290e-01 -7.07106781e-01]
 [-5.77350269e-01 -4.08248290e-01  7.07106781e-01]]
[[-1.73205081 -4.04145188 -2.30940108]
 [ 0.         -4.0824829   3.26598632]
 [ 0.          0.          2.82842712]]
[[ 1. -1.  4.]
 [ 1.  4. -2.]
 [ 1.  4.  2.]]


# Chapter 10: Matrix Row Operations and Echelon Form

## Row Echelon Form and Gaussian Elimination

Operasi baris elementer (Elementary Row Operations) adalah sekumpulan manipulasi matematika—termasuk pertukaran baris, perkalian baris dengan skalar, dan penjumlahan kelipatan suatu baris ke baris lain—yang digunakan untuk menyederhanakan matriks tanpa mengubah solusi dari sistem linear yang diwakilinya. Tujuan utama dari operasi ini adalah mengubah matriks menjadi Row Echelon Form (REF) atau Reduced Row Echelon Form (RREF) melalui eliminasi Gaussian. Bentuk ini mempermudah pencarian solusi sistem persamaan linear dan penentuan nilai rank matriks secara manual maupun komputasi.

In [2]:
import numpy as np

A = np.array([[1, 2, 3], [2, 5, 8], [3, 8, 14]], dtype=float)

A[1] = A[1] - 2 * A[0]
A[2] = A[2] - 3 * A[0]
A[2] = A[2] - 2 * A[1]

print(A)

[[1. 2. 3.]
 [0. 1. 2.]
 [0. 0. 1.]]


# Chapter 11: Matrix Rank

## Concept of Matrix Rank and Linear Independence

Rank dari sebuah matriks menunjukkan jumlah maksimum baris atau kolom yang saling bebas linear (linearly independent) di dalam matriks tersebut. Nilai rank memberikan informasi mengenai dimensi dari ruang bagian (subspace) yang dijangkau oleh kolom-kolom matriks tersebut. Jika sebuah matriks persegi berdimensi $N \times N$ memiliki rank sama dengan $N$, maka matriks tersebut dikatakan memiliki full rank dan dipastikan memiliki invers. Namun, jika rank kurang dari $N$, matriks tersebut disebut rank-deficient atau singular. Di NumPy, fungsi `np.linalg.matrix_rank()` digunakan untuk menghitung nilai ini secara otomatis menggunakan dekomposisi nilai singular.

In [3]:
import numpy as np

A = np.array([[1, 2, 3], [2, 4, 6], [1, 5, 7]])
rank_A = np.linalg.matrix_rank(A)

print(rank_A)

2


# Chapter 12: Determinant

## Matrix Determinant and Geometric Scaling

Determinant adalah sebuah nilai skalar tunggal yang dapat dihitung dari matriks persegi. Secara geometri, nilai absolut dari determinan merepresentasikan faktor penskalaan volume atau luas ruang yang ditransformasikan oleh matriks tersebut. Jika determinan bernilai nol, hal itu menandakan bahwa matriks telah mengompresi seluruh ruang ke dimensi yang lebih rendah (kehilangan informasi) sehingga tidak memiliki invers (singular). Di dalam NumPy, perhitungan nilai determinan ini difasilitasi oleh fungsi `np.linalg.det()`.

In [4]:
import numpy as np

A = np.array([[1, 3], [2, 4]])
det_A = np.linalg.det(A)

print(det_A)

-2.0


# Chapter 13: Eigenvalues and Eigenvectors

## Eigenvalues and Eigenvectors Derivation

Eigenvector (vektor karakteristik) dari sebuah matriks transformasi adalah vektor non-nol yang arahnya tidak berubah ketika dikalikan dengan matriks tersebut, melainkan hanya mengalami perubahan skala (panjang). Nilai faktor perubahan skala tersebut dinamakan Eigenvalue (nilai karakteristik), yang dinotasikan dengan skalar $\lambda$. Secara matematis, hubungan ini dirumuskan sebagai $Av = \lambda v$. Di dalam NumPy, kita dapat menemukan seluruh nilai eigenvalue dan eigenvector dari sebuah matriks persegi secara simultan menggunakan fungsi `np.linalg.eig()`.

In [5]:
import numpy as np

A = np.array([[1, 2], [2, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[ 3. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


# Chapter 14: Singular Value Decomposition (SVD)

## Singular Value Decomposition (SVD)

Singular Value Decomposition (SVD) adalah metode dekomposisi matriks yang bersifat universal karena dapat diterapkan pada matriks berdimensi apa saja, baik persegi maupun persegi panjang ($M \times N$). SVD memecah matriks $A$ menjadi perkalian tiga matriks komponen: $A = U \Sigma V^T$. Matriks $U$ berisi vektor singular kiri (left singular vectors), $\Sigma$ adalah matriks diagonal yang berisi nilai singular (singular values) yang diurutkan dari terbesar ke terkecil untuk menunjukkan tingkat kepentingan informasi, dan $V^T$ berisi vektor singular kanan (right singular vectors). NumPy menyediakan fungsi `np.linalg.svd()` untuk menghitung ketiga matriks ini secara langsung.

In [6]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
U, Sigma, Vt = np.linalg.svd(A)

print(U)
print(Sigma)
print(Vt)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


# Chapter 15: Quadratic Form and PCA

## Principal Component Analysis (PCA)

Principal Component Analysis (PCA) adalah teknik reduksi dimensi yang digunakan untuk menyederhanakan dataset besar dengan cara memproyeksikan data tersebut ke dalam sumbu baru yang disebut Principal Components (PC). Sumbu baru ini diperoleh dari eigenvector dari matriks kovarians data yang memiliki eigenvalue terbesar. Proses ini memastikan bahwa varians atau informasi maksimal dari data asli tetap dipertahankan meskipun jumlah dimensinya telah dikurangi.

In [7]:
import numpy as np

X = np.array([[1, 2], [3, 4], [5, 6]], dtype=float)
X_centered = X - np.mean(X, axis=0)
cov_matrix = np.cov(X_centered.T)

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
PC = X_centered @ eigenvectors

print(PC)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


# Chapter 16: Linear Least-Squares Regression

## Linear Least-Squares Solution via Normal Equation

Regresi kuadrat terkecil (Linear Least-Squares Regression) bertujuan untuk menemukan garis tren terbaik yang meminimalkan total kuadrat jarak (residual) antara titik data asli dengan garis prediksi. Dalam aljabar linear, solusi optimum untuk bobot model atau koefisien regresi ($\beta$) dapat dihitung secara analitis menggunakan Persamaan Normal (Normal Equation): $\beta = (X^T X)^{-1} X^T y$. Di sini, $X$ adalah matriks desain yang berisi fitur data (ditambah kolom konstanta/bias), dan $y$ adalah vektor target. NumPy memanfaatkan operasi perkalian matriks, transpose, dan invers untuk menyelesaikan persamaan ini dalam satu langkah komputasi.

In [8]:
import numpy as np

X_data = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 5, 4, 6])

X = np.vstack([np.ones(len(X_data)), X_data]).T
beta = np.linalg.inv(X.T @ X) @ X.T @ y

print(beta)

[1.3 0.9]
