<a href="https://colab.research.google.com/github/Keistkmiya/Tugas3-Practical_Linear_Algebra_for_Data_Science/blob/main/Tugas3_Chapter5_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 5: Matrices, Part 1

## Matrix Anatomy and Creation in NumPy

Matriks adalah sekumpulan angka yang disusun dalam struktur dua dimensi berupa baris (rows) dan kolom (columns). Dimensi dari matriks ditentukan oleh jumlah baris dikali jumlah kolom ($M \times N$). Dalam data science, matriks sering kali merepresentasikan sebuah dataset, di mana baris mewakili sampel/observasi dan kolom mewakili fitur (features). NumPy mempermudah pembuatan matriks baik secara manual menggunakan list bersarang (nested lists) maupun menggunakan fungsi bawaan untuk membuat matriks khusus seperti matriks nol (zeros) atau matriks identitas.

In [1]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])

M_zeros = np.zeros((2, 3))
M_identity = np.eye(3)

print("Matriks A:\n", A)
print("\nMatriks Nol:\n", M_zeros)
print("\nMatriks Identitas:\n", M_identity)

Matriks A:
 [[1 2 3]
 [4 5 6]]

Matriks Nol:
 [[0. 0. 0.]
 [0. 0. 0.]]

Matriks Identitas:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Matrix Addition, Subtraction, and Scalar Multiplication

Sama seperti pada vektor, operasi penjumlahan dan pengurangan antar-matriks dilakukan secara elemen demi elemen (element-wise). Oleh karena itu, dua matriks hanya dapat dijumlahkan atau dikurangkan jika memiliki dimensi yang benar-benar sama (homogen). Untuk perkalian matriks dengan skalar, setiap elemen di dalam matriks akan dikalikan dengan nilai skalar tersebut, yang secara geometris berarti mengubah skala dari seluruh ruang yang direpresentasikan oleh matriks tersebut.

In [2]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

A_plus_B = A + B
A_minus_B = A - B
A_scaled = A * 2

print("Penumlahan:\n", A_plus_B)
print("\nPengurangan:\n", A_minus_B)
print("\nPerkalian Skalar:\n", A_scaled)

Penumlahan:
 [[ 6  8]
 [10 12]]

Pengurangan:
 [[-4 -4]
 [-4 -4]]

Perkalian Skalar:
 [[2 4]
 [6 8]]


## Transpose Operation

Operasi transpose adalah proses mengubah struktur matriks dengan cara menukar posisi baris menjadi kolom, dan posisi kolom menjadi baris. Jika matriks awal $A$ memiliki dimensi $M \times N$, maka matriks transpose (dinotasikan dengan $A^T$ atau $A^H$) akan memiliki dimensi $N \times M$. Operasi ini sangat sering digunakan dalam manipulasi aljabar linear untuk menyamakan dimensi sebelum melakukan operasi perkalian dot product. Di NumPy, kita bisa menggunakan atribut `.T` untuk melakukan transpose dengan sangat cepat.

In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])

A_transpose = A.T

print("Matriks Asli (2x3):\n", A)
print("\nMatriks Transpose (3x2):\n", A_transpose)

Matriks Asli (2x3):
 [[1 2 3]
 [4 5 6]]

Matriks Transpose (3x2):
 [[1 4]
 [2 5]
 [3 6]]


## Diagonal and Triangular Matrices

Matriks diagonal adalah matriks persegi di mana semua elemen di luar diagonal utamanya bernilai nol. Matriks ini sangat efisien dalam komputasi karena operasi perkaliannya hanya melibatkan elemen diagonalnya saja. Sementara itu, matriks segitiga dibagi menjadi dua jenis: Upper Triangular (segitiga atas), di mana semua elemen di bawah diagonal utama bernilai nol, dan Lower Triangular (segitiga bawah), di mana semua elemen di atas diagonal utama bernilai nol. Jenis matriks ini memegang peran penting dalam metode dekomposisi matriks seperti LU Decomposition.

In [4]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

diagonal_elements = np.diag(A)
diagonal_matrix = np.diag(diagonal_elements)

upper_triangular = np.triu(A)
lower_triangular = np.tril(A)

print("Elemen diagonal utama:", diagonal_elements)
print("\nMatriks Diagonal:\n", diagonal_matrix)
print("\nMatriks Segitiga Atas (Upper):\n", upper_triangular)
print("\nMatriks Segitiga Bawah (Lower):\n", lower_triangular)

Elemen diagonal utama: [1 5 9]

Matriks Diagonal:
 [[1 0 0]
 [0 5 0]
 [0 0 9]]

Matriks Segitiga Atas (Upper):
 [[1 2 3]
 [0 5 6]
 [0 0 9]]

Matriks Segitiga Bawah (Lower):
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


## Symmetric Matrix

Sebuah matriks persegi dikatakan simetris jika hasil transpose dari matriks tersebut sama dengan matriks asalnya, atau memenuhi syarat $A = A^T$. Dalam struktur data matriks simetris, elemen pada baris ke-$i$ kolom ke-$j$ akan selalu sama dengan elemen pada baris ke-$j$ kolom ke-$i$ ($a_{ij} = a_{ji}$). Matriks simetris ini merupakan salah satu bentuk matriks yang paling sering dijumpai dalam data science, contohnya pada matriks korelasi atau matriks kovarians yang mengukur hubungan antar-fitur.

In [5]:
import numpy as np

S = np.array([[1, 4, 5], [4, 2, 6], [5, 6, 3]])

is_symmetric = np.array_equal(S, S.T)

print("Matriks S:\n", S)
print("\nApakah matriks S simetris?", is_symmetric)

Matriks S:
 [[1 4 5]
 [4 2 6]
 [5 6 3]]

Apakah matriks S simetris? True


# Chapter 6: Matrices, Part 2

## Matrix-Vector Multiplication

Perkalian antara matriks dan vektor dapat dipandang sebagai transformasi linear, di mana matriks bertindak sebagai operator yang mengubah posisi, arah, atau skala dari vektor tersebut. Agar perkalian ini valid, jumlah kolom pada matriks harus sama dengan jumlah elemen (baris) pada vektor. Secara matematis, setiap baris pada matriks akan dihitung dot product-nya dengan vektor tersebut untuk menghasilkan elemen-elemen baru pada vektor keluaran. Di NumPy, operasi ini dilakukan menggunakan fungsi `np.dot()` atau operator `@`.

In [6]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
v = np.array([0.5, 2])

result = A @ v
print("Hasil Matrix-Vector Multiplication:\n", result)

Hasil Matrix-Vector Multiplication:
 [ 4.5  9.5 14.5]


## Matrix-Matrix Multiplication

Perkalian antara dua matriks ($A \times B$) tidak dilakukan secara elemen demi elemen, melainkan dengan menghitung dot product antara baris-baris pada matriks pertama dengan kolom-kolom pada matriks kedua. Syarat mutlak operasi ini adalah jumlah kolom matriks pertama harus sama dengan jumlah baris matriks kedua. Jika matriks $A$ berdimensi $M \times K$ dan matriks $B$ berdimensi $K \times N$, maka matriks hasil $C$ akan memiliki dimensi $M \times N$. Perlu diingat bahwa perkalian matriks tidak bersifat komutatif ($A \times B \neq B \times A$).

In [7]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.dot(A, B)
print("Hasil Perkalian Matriks A dan B:\n", C)

# Membuktikan tidak komutatif
print("\nApakah AB sama dengan BA?")
print(np.array_equal(np.dot(A, B), np.dot(B, A)))

Hasil Perkalian Matriks A dan B:
 [[19 22]
 [43 50]]

Apakah AB sama dengan BA?
False


## Hadamard Product (Element-wise Multiplication)

Berbeda dengan perkalian matriks standar yang menggunakan dot product, Hadamard Product adalah operasi perkalian matriks yang dilakukan secara elemen demi elemen (element-wise multiplication). Simbol matematis untuk operasi ini biasanya dinotasikan dengan $\odot$. Agar operasi ini dapat dilakukan, kedua matriks wajib memiliki dimensi yang benar-benar identik ($M \times N$). Di dalam NumPy, jika kita ingin melakukan perkalian jenis ini, kita cukup menggunakan operator bintang standar (`*`).

In [8]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

hadamard_result = A * B
print("Hasil Hadamard Product (A * B):\n", hadamard_result)

Hasil Hadamard Product (A * B):
 [[ 5 12]
 [21 32]]


## Matrix Frobenius Norm

Frobenius Norm adalah cara untuk mengukur "ukuran" atau magnitudo total dari sebuah matriks, mirip seperti menghitung panjang pada vektor. Secara matematis, Frobenius Norm (dinotasikan dengan $||A||_F$) dihitung dengan mengkuadratkan setiap elemen di dalam matriks, menjumlahkan seluruh hasil kuadrat tersebut, lalu mencari akar kuadrat dari total penjumlahannya. Di dalam machine learning, Frobenius Norm sering digunakan sebagai bagian dari fungsi penalti (regularisasi) untuk mencegah model menjadi terlalu kompleks. NumPy menyediakan fungsi `np.linalg.norm()` yang secara otomatis akan menghitung nilai ini jika input yang dimasukkan berupa matriks.

In [9]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

frobenius_norm = np.linalg.norm(A)
print("Nilai Frobenius Norm dari matriks A:", frobenius_norm)

Nilai Frobenius Norm dari matriks A: 5.477225575051661


# Chapter 7: Matrix Applications

## Geometric Transformations via Matrix Multiplication

Salah satu aplikasi paling nyata dari perkalian matriks dalam ilmu komputer dan data science adalah transformasi geometri, seperti rotasi, penskalaan (scaling), dan pencerminan (reflection). Sebuah objek geometris atau sekumpulan koordinat data dapat direpresentasikan sebagai matriks. Dengan mengalikan matriks koordinat tersebut dengan "matriks transformasi" khusus, kita dapat mengubah posisi atau bentuk seluruh objek secara serentak. Sebagai contoh, sebuah matriks rotasi menggunakan fungsi trigonometri untuk memutar koordinat data sebesar sudut tertentu ($\theta$) terhadap titik pusat.

In [10]:
import numpy as np

v = np.array([1, 0])

theta = np.pi / 2
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])

v_rotated = R @ v
print("Koordinat awal:", v)
print("Koordinat setelah rotasi 90 derajat:\n", np.round(v_rotated))

Koordinat awal: [1 0]
Koordinat setelah rotasi 90 derajat:
 [0. 1.]


## Image Processing as Matrix Manipulation

Dalam ranah computer vision, sebuah gambar berskala keabu-abuan (grayscale image) direpresentasikan secara digital sebagai matriks dua dimensi. Setiap elemen di dalam matriks tersebut menyimpan nilai intensitas kecerahan pixel, biasanya berkisar antara 0 (hitam pekat) hingga 255 (putih cerah). Operasi pemrosesan citra tingkat dasar, seperti meningkatkan kecerahan (brightness modification) atau membalikkan warna (inverting image), dapat dilakukan dengan sangat cepat menggunakan operasi aritmetika matriks standar di NumPy.

In [11]:
import numpy as np

image_matrix = np.array([[50,  100, 150],
                         [200, 255, 100],
                         [20,  80,  130]])

darker_image = np.uint8(image_matrix * 0.5)

inverted_image = 255 - image_matrix

print("Gambar asli:\n", image_matrix)
print("\nGambar lebih gelap:\n", darker_image)
print("\nGambar inversi:\n", inverted_image)

Gambar asli:
 [[ 50 100 150]
 [200 255 100]
 [ 20  80 130]]

Gambar lebih gelap:
 [[ 25  50  75]
 [100 127  50]
 [ 10  40  65]]

Gambar inversi:
 [[205 155 105]
 [ 55   0 155]
 [235 175 125]]


# Chapter 8: Matrix Inverse

## Concept of Matrix Inverse

Invers matriks adalah kebalikan dari suatu matriks persegi, yang jika dikalikan dengan matriks asalnya akan menghasilkan matriks identitas ($A \times A^{-1} = I$). Dalam aljabar linear, operasi pembagian matriks tidak didefinisikan secara langsung, sehingga peran pembagian tersebut digantikan oleh perkalian dengan matriks invers. Tidak semua matriks memiliki invers; matriks yang tidak memiliki invers disebut matriks singular, yang terjadi jika nilai determinannya sama dengan nol. Di NumPy, invers matriks dapat dihitung menggunakan fungsi `np.linalg.inv()`.

In [12]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)

print(A_inv)
print(np.round(A @ A_inv))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]
